[package]
name = "hardlight"
version = "0.1.0"
edition = "2021"
description = "placeholder"
authors = ["Azz <azz@valera.co>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = { version = "0.18.0", features = ["rustls-tls-native-roots", "rustls-tls-webpki-roots"] }

[workspace]
members = [
    ".",
    "testing-project"
]
